// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtk-0wOKcPsXaO3ndzZmK3SkyLj5TM2dk',
    appId: '1:1048261543994:web:894d0021cebe2980094d03',
    messagingSenderId: '1048261543994',
    projectId: 'todoapp-88006',
    authDomain: 'todoapp-88006.firebaseapp.com',
    storageBucket: 'todoapp-88006.appspot.com',
    measurementId: 'G-JJ97GSZCW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwoeIPirvXODwepcPg5NOHpy4uZgu_VQ',
    appId: '1:1048261543994:android:9214dbaba920fd42094d03',
    messagingSenderId: '1048261543994',
    projectId: 'todoapp-88006',
    storageBucket: 'todoapp-88006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoiNTg6rGxAXF5VNA31TRNdl9Iaa7ryhk',
    appId: '1:1048261543994:ios:a1f1cc89a0e7c6df094d03',
    messagingSenderId: '1048261543994',
    projectId: 'todoapp-88006',
    storageBucket: 'todoapp-88006.appspot.com',
    androidClientId:
        '1048261543994-0ju7olb9cs9tvjlvdbsra0obcnh1adn2.apps.googleusercontent.com',
    iosClientId:
        '1048261543994-s7o0pmabh80db45npggkt6sndskang8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoiNTg6rGxAXF5VNA31TRNdl9Iaa7ryhk',
    appId: '1:1048261543994:ios:a1f1cc89a0e7c6df094d03',
    messagingSenderId: '1048261543994',
    projectId: 'todoapp-88006',
    storageBucket: 'todoapp-88006.appspot.com',
    androidClientId:
        '1048261543994-0ju7olb9cs9tvjlvdbsra0obcnh1adn2.apps.googleusercontent.com',
    iosClientId:
        '1048261543994-s7o0pmabh80db45npggkt6sndskang8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
